const NotificationName ={
	// 趋势模块
	// 修改dateRange
	DID_CHANGE_DATE_RANGE: 'DID_CHANGE_DATE_RANGE',
	// 点击收藏按钮
	DID_SELECTE_FAVORITE: 'DID_SELECTE_FAVORITE',

	// 切换了tab
	DID_CHANGE_TAB: 'DID_CHANGE_TAB',

	DID_CHANGE_FAVORITE_STATE_POPULAR: 'DID_CHANGE_FAVORITE_STATE_POPULAR',
	DID_CHANGE_FAVORITE_STATE_TRENDING: 'DID_CHANGE_FAVORITE_STATE_TRENDING',
}

export default NotificationName;